apiVersion: v1
kind: Secret
metadata:
    name: pg-admin-secrets
type: Opaque
data:
    # Base64 encode
    PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ== # superman@google.com
    DB_PASSWORD: bXlwb3N0Z3Jlc3Bhc3N3b3Jk # mypostgrespassword
