apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
type: Opaque
data:
    # Base64 encode
    DB_USER: cG9zdGdyZXM= # postgres = cG9zdGdyZXM=
    DB_PASSWORD: bXlwb3N0Z3Jlc3Bhc3N3b3Jk # mypostgrespassword = bXlwb3N0Z3Jlc3Bhc3N3b3Jk
