name: Secure docker image

on:
    push:
        branches: ['main']
        paths: ['secure-docker-image/**']
jobs:
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install
              working-directory: ./secure-docker-image

            - name: Run vulnerability check
              run: sh check-dependencies.sh
              working-directory: ./secure-docker-image

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build local container
              uses: docker/build-push-action@v4
              with:
                  tags: localbuild/task-runner:latest
                  push: false
                  load: true

            - name: Scan image
              uses: anchore/scan-action@v3
              with:
                  image: 'localbuild/task-runner:latest'
                  fail-build: true
                  severity-cutoff: critical

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./secure-docker-image
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-runner
